### PR TITLE
fix #4141: Avoid redundant `this` access during async function lowering

### LINKED ISSUE #4141: Async transformation causes `this` access before `super()` call
## Input code
```
new (class Foo extends class { } {
	constructor() {
		let x = 1;
		(async () => {
			console.log("before super", x);  // (1) Sync phase
			await 1;
			console.log("after super", x);   // (2) Async phase
		})();
		super();
		x = 2;
	}
})();
```

## Esbuild playground
https://esbuild.github.io/try/#dAAwLjI1LjIALS10YXJnZXQ9ZXMyMDE2AG5ldyAoY2xhc3MgRm9vIGV4dGVuZHMgY2xhc3MgeyB9IHsKCWNvbnN0cnVjdG9yKCkgewoJCWxldCB4ID0gMTsKCQkoYXN5bmMgKCkgPT4gewoJCQljb25zb2xlLmxvZygiYmVmb3JlIHN1cGVyIiwgeCk7CgkJCWF3YWl0IDE7CgkJCWNvbnNvbGUubG9nKCJhZnRlciBzdXBlciIsIHgpOwoJCX0pKCk7CgkJc3VwZXIoKTsKCQl4ID0gMjsKCX0KfSkoKTsK

## Expected Behavior
The code should output:
```
before super 1
after super 2
```

## Actual Behavior
Throws a reference error:
```
Uncaught ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
```

### PR DESCRIPTION
**Pull request by magic-akari**
- Fix: #4141

### CODE REVIEW

**Comment by thorn0** [comment]
Tiny note from someone maintaining legacy codebases — this change might have similar side effects to [this recent SWC issue](https://github.com/swc-project/swc/issues/10374). Just wanted to raise it in case it’s relevant. Appreciate the great work 🙏

File: internal/js_parser/js_parser_lower_test.go [hunk 1]
```diff
@@ -241,7 +241,7 @@ func TestLowerAsyncFunctions(t *testing.T) {
 }
 `)
 	// Skip forwarding altogether when parameter evaluation obviously cannot throw
-	expectPrintedTarget(t, 2015, "async (a, b = 123) => {console.log(a, b);}", `(a, b = 123) => __async(this, null, function* () {
```
Comment (Randallstrader1221) [inline internal/js_parser/js_parser_lower_test.go:244]: - @gh repo clone microsoft/vscode-mock-debug

**Review by Randallstrader1221 — CHANGES_REQUESTED** [review]
76166681060

**Review by Randallstrader1221 — APPROVED** [review]
